### ISSUE TITLE
OS specificity workaround

### ISSUE THREAD

**Issue by RM35M4419** [whateverforever/zettelwarmer#2]
Hey! Love the idea and the script works great.
I was looking for a method / process / habit of reviewing old notes and this fits perfectly.

On Linux, I had to change line 152 with:
`subprocess.run(["xdg-open", zettel])`
This code does not necessarily work on any Linux.

As a broader solution, I replaced the same line with:
```
try:
    subprocess.run(["open", zettel]) #original command for Mac
except:
    subprocess.run(["xdg-open", zettel])
```
 

It should work on Mac and several Linux distros. 
It should be expanded to include Windows systems, and I'm sure there are way more elegant solutions for this.

**Comment by whateverforever** [comment]
Thanks for the heads-up, I will add that. Apparently under windows it's just the filename.. Maybe I'll try that too (even though I won't be able to verify that it works)

**Comment by whateverforever** [comment]
I added it, please tell me if it works like this

**Comment by RM35M4419** [comment]
Yes, it works ok in linux.  And I like your _if_ solution better.
Cheers!
